version: '3'
services:
  frontend:
    build: .
    image: katharostech/quasar-cli:latest
    command: sh
    ports: 
      - "8080:8080"
    #volumes: 
    #  - .:/home/node/app:rw

    #volumes:
      - .:/opt/app
      - /opt/app/node_modules

    restart: "no"
    stdin_open: true
    #ports:
    #  - 8080:8080
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
